# For per pipeline config, check docs: https://www.elastic.co/guide/en/logstash/current/logstash-settings-file.html

- pipeline.id: main
  path.config: "/usr/share/logstash/pipeline/main.conf"
  queue.type: memory

- pipeline.id: coin_gecko
  path.config: "/usr/share/logstash/pipeline/coin_gecko.conf"
  queue.type: memory

- pipeline.id: coin_gecko2
  path.config: "/usr/share/logstash/pipeline/coin_gecko2.conf"
  queue.type: memory

# - pipeline.id: pubsub_ideas
#   path.config: "/usr/share/logstash/pipeline/pubsub_ideas.conf"
#   queue.type: memory

# - pipeline.id: mongo_news
#   path.config: "/usr/share/logstash/pipeline/mongo_news.conf"
#   queue.type: memory

